NBP_I_PROJEKAT/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.SignalR;
using System.Threading.Tasks;
using StackExchange.Redis;
using Neo4jClient;
using Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Neo4j.Driver;
using NBP_I_PROJEKAT.Session;
using NBP_I_PROJEKAT.Hubs;
using NBP_I_PROJEKAT.Extensions;
using NBP_I_PROJEKAT.Models;
using System.Text.Encodings.Web;
using Microsoft.Extensions.Logging;
using NBP_I_PROJEKAT;
using System.Diagnostics;

namespace NBP_I.Controllers
{

    public class HomeController : Controller
    {

        public readonly IDriver _driver;
        public readonly IConnectionMultiplexer _redis;
        public readonly IHubContext<ObjavaHub> _hub;
        public readonly ILogger<HomeController> _logger;
        public (UserInfo, int)[] Leaderboard => RedisManager<UserInfo>.GetSortedSet("leaderboard", 10);

        public static readonly object _lock = new();
        public static bool _firstTimeRun = true;
        
        public HomeController(IDriver driver, IHubContext<ObjavaHub> hub, IConnectionMultiplexer redis, ILogger<HomeController> logger)
        {
            _driver = driver;
            _hub = hub;
            _logger = logger;
            _redis = redis;

            lock (_lock)
            {
                if (!_firstTimeRun)
                    return;
                _firstTimeRun = false;

                RedisManager<Notifikacija>.Subscribe("PostavljenaObjava", async (channel, data) =>
                {
                    data.Pratioci.ToList().ForEach(x => RedisManager<string>
                        .Push($"korisnici:{x}:notifikacije", $"{data.KorisnickoIme} kog pratite je postavio novu objavu - {data.ObjavaName} - | {data.ObjavaId}"));
                    await hub.Clients.All.SendAsync("PrimljenaNotifikacija", data);
                });
            }
        }
        public async Task<IActionResult> Index()
        {

            List<Tag> tagList;
            List<Objava> objavaList = null;
            List<Objava> objavaPreporukeList = null;



            IResultCursor result;
            IAsyncSession session = _driver.AsyncSession();
            try
            {
                // Pokupi sve tagove
                result = await session.RunAsync($"MATCH (t:Tag) RETURN t");



                tagList = (await result.ToListAsync()).Select(t =>
                {
                    INode tag = t["t"].As<INode>();
                    return new Tag
                    {
                        Id = (int)tag.Id,
                        Naziv = tag.Properties["naziv"].ToString()
                    };
                }).ToList();



                // Nadji sve tagove koji imaju objave i dodaj te objave u njihovu listu objava
                await Task.WhenAll(tagList.Select(async x =>
                {
                    session = _driver.AsyncSession();
                    result = await session.RunAsync($"MATCH (t:Tag {{naziv: '{x.Naziv}'}})-[r]-(o:Objava) return o");
                    var veze = await result.ToListAsync();
                    veze.ForEach(v =>
                    {
                        INode v1 = v["o"].As<INode>();
                        var o = new Objava
                        {
                            Id = (int)v1.Id,
                            Naziv = v1.Properties["naziv"].ToString(),
                            Sadrzaj = v1.Properties["sadrzaj"].ToString(),
                            Tag = v1.Properties["tag"].ToString()
                            
                        };
                        x.Objave.Add(o);
                    });
                }));



                var userId = HttpContext.Session.GetUserId();
                if (userId >= 0)
                {
                    
                    session = _driver.AsyncSession();
                    result = await session.RunAsync(@$"MATCH (k:Korisnik)-[r:VISITED]-(o:Objava) 
                                    WHERE id(k)={userId} 
                                    RETURN o, r, k");
                    objavaList = (await result.ToListAsync()).Select(o =>
                    {
                        INode oo = o["o"].As<INode>();
                        return new Objava
                        {
                            Id = (int)oo.Id,
                            Naziv = oo.Properties["naziv"].ToString(),
                            Sadrzaj = oo.Properties["sadrzaj"].ToString(),
                            Tag = oo.Properties["tag"].ToString()    
                        };
                    }).ToList();


                    session = _driver.AsyncSession();
                    result = await session.RunAsync(@$"MATCH (k:Korisnik)-[r:LIKED]-(o:Objava) 
                                    WHERE id(k)={userId} 
                                    RETURN o.tag
                                    LIMIT 5");
                    var fav = await result.ToListAsync();
                    if (fav.Count > 0)
                    {
                        
                        var favTag = fav[0].Values.Values.FirstOrDefault().ToString();
                        //var favTag = fav[0].Values.FirstOrDefault().ToString();

                        session = _driver.AsyncSession();
                     
                        result = await session.RunAsync(@$"MATCH (o:Objava) 
                                    WHERE o.tag = '{favTag}' 
                                    RETURN o");

                        objavaPreporukeList = (await result.ToListAsync()).Select(o =>
                        {
                            INode oo = o["o"].As<INode>();
                            Objava obj = new()
                            {
                                Id = (int)oo.Id,
                                Naziv = oo.Properties["naziv"].ToString(),
                                Sadrzaj = oo.Properties["sadrzaj"].ToString(),
                                Tag = oo.Properties["tag"].ToString()
                                
                            };
                            return obj;
                        }).Where(x => objavaList.Find(y => x.Id == y.Id) == null).ToList();
                    }
                }
            }
            finally
            {
                await session.CloseAsync();
            }
            return View(new Objave { TagList = tagList, ObjavaList = objavaList, ObjavaRecomendList = objavaPreporukeList, Leaderboard = Leaderboard });
        }
        public IActionResult Login()
        {
            if (!HttpContext.Session.IsUsernameEmpty())
                return RedirectToAction("Index","Home");

            return View();
        }
        public IActionResult Register()
        {
            if (!HttpContext.Session.IsUsernameEmpty())
                return RedirectToAction("Index");

            return View();
        }
        public IActionResult Odjava()
        {
            if (!HttpContext.Session.IsLoggedIn())
                return RedirectToAction("Login", "Home");

            HttpContext.Session.Clear();

            return RedirectToAction("Index", "Home");
        }
        [HttpGet]
        [Route("PrikaziSveObjaveKorisnika")]
        public async Task<IActionResult> PrikaziSveObjaveKorisnika(int userId)//radi
        {
            List<Objava> objavaList = null;
            IResultCursor result;
            IAsyncSession session = _driver.AsyncSession();
            try
            {
                result = await session.RunAsync($"MATCH (k:Korisnik)-[r:POSTED]->(o:Objava) WHERE id(k) = {userId} RETURN o");
                var list = await result.ToListAsync();



                if (list.Count > 0)
                {
                    Korisnik k = new Korisnik { ID = userId };
                    objavaList = new List<Objava>();
                    list.ForEach(x =>
                    {
                        INode objava = x["o"].As<INode>();
                        objavaList.Add(new Objava
                        {
                            Id = (int)objava.Id,
                            Naziv = objava.Properties["naziv"].ToString(),
                            Sadrzaj = objava.Properties["sadrzaj"].ToString(),
                            Tag = objava.Properties["tag"].ToString(),
                            Korisnik = k
                            
                        });
                    });
                }
            }
            finally
            {
                await session.CloseAsync();
            }
            return View(objavaList);
        }

        [HttpPost]
        [Route("Registracija")]
        public async Task<IActionResult> Registracija(string email, string korisnickoIme, string sifra, string fakultet, string smer, int godinaStudija)
        {

            if (HttpContext.Session.IsLoggedIn())
            {
                

                return RedirectToAction("Index", "Home");
            }

            var session = _driver.AsyncSession();
            try
            {
                var result = await session.RunAsync($"CREATE (k:Korisnik {{email: '{email}', korisnickoIme: '{korisnickoIme}', sifra:  '{sifra}', fakultet: '{fakultet}', smer:  '{smer}', godinaStudija: {godinaStudija} }}) return id(k)");
                var userId = await result.SingleAsync(record => record["id(k)"].As<int>());
                if (userId != -1)
                {
                    HttpContext.Session.SetString(SessionKeys.Username, korisnickoIme);
                    HttpContext.Session.SetInt32(SessionKeys.UserId, userId);
                    return RedirectToAction("Login", "Home");
                }
            }
            finally
            {
                await session.CloseAsync();
            }

            return RedirectToAction("Register", "Home");
        }

NBP_I_PROJEKAT/Controllers/ObjavaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.SignalR;
using System.Threading.Tasks;
using StackExchange.Redis;
using Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation;
using Neo4jClient;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Neo4j.Driver;
using NBP_I_PROJEKAT.Session;
using NBP_I_PROJEKAT.Hubs;
using NBP_I_PROJEKAT.Extensions;
using NBP_I_PROJEKAT.Models;
using Microsoft.Extensions.Logging;

namespace NBP_I_PROJEKAT.Controllers
{
   
    public class ObjavaController:Controller
    {
        private readonly IDriver _driver;
        private readonly IConnectionMultiplexer _redis;
        private readonly IHubContext<ObjavaHub> _hub;
        public readonly ILogger<ObjavaController> _logger;


        private static readonly object _lock = new();
        private static bool _firstTimeRun = true;
        public (UserInfo, int)[] Leaderboard => RedisManager<UserInfo>.GetSortedSet("leaderboard", 10);
        public ObjavaController(IDriver driver, IHubContext<ObjavaHub> hub, IConnectionMultiplexer redis, ILogger<ObjavaController> logger)
        {
            _driver = driver;
            _logger = logger;
            _hub = hub;
            _redis = redis;

            
        }
        public IActionResult Index()
        {
            return View();

        }
        [HttpPost]
        [Route("DodajObjavu")]
        public async Task<IActionResult> DodajObjavu(string Naziv, string Sadrzaj, string Tag)//ovo radi xd
        {

            if (!HttpContext.Session.IsLoggedIn())
            {

                return StatusCode(401, "Niste logovani!");
            }
            IResultCursor result;

            var session = _driver.AsyncSession();
            try
            {
                var res = await (await session.RunAsync($"MATCH (t:Tag {{ naziv: '{Tag}' }}) RETURN id(t)")).ToListAsync();
                int tagID = -1;
                if (res.Count == 0)
                {
                    result = await session.RunAsync($"CREATE (tag:Tag {{ naziv: '{Tag}' }}) return id(tag)");
                    tagID = await result.SingleAsync(record => record["id(tag)"].As<int>());
                }
                else
                {
                    tagID = res[0]["id(t)"].As<int>();
                }
                var idUser = HttpContext.Session.GetUserId();
                result = await session.RunAsync($"CREATE (o:Objava {{ naziv: '{Naziv}', sadrzaj: '{Sadrzaj}', tag: '{Tag}', datumkreiranja: '{DateTime.Now}',likes:'{null}',poruke:'{null}'}}) return id(o)");
                var objavaID = await result.SingleAsync(record => record["id(o)"].As<int>());
                if (objavaID == -1)
                    return RedirectToAction("Index", "Home");
                //return BadRequest("Nije kreirana objava");

                session = _driver.AsyncSession();
                result = await session.WriteTransactionAsync(tx => tx.RunAsync(@$"MATCH(t:Tag) WHERE id(t)={tagID} 
                                    MATCH (o:Objava) WHERE id(o)={objavaID} 
                                    CREATE (t)-[:HAS]->(o)"));

                var userId = HttpContext.Session.GetUserId();
                session = _driver.AsyncSession();
                result = await session.WriteTransactionAsync(tx => tx.RunAsync(@$"MATCH(k:Korisnik) WHERE id(k)={userId} 
                                    MATCH (o:Objava) WHERE id(o)={objavaID} 
                                    CREATE (k)-[:POSTED]->(o)"));

                try //to je pubsub mehanizam to cemo posle
                {
                    result = await session.RunAsync($"MATCH p=(k1:Korisnik)-[r:PRATI]->(k2:Korisnik) WHERE id(k2)={userId} RETURN id(k1)");
                    var idList = await result.ToListAsync();
                    var ids = idList?.Select(x => x["id(k1)"].As<string>()).ToArray() ?? Array.Empty<string>();

                    var userName = HttpContext.Session.GetUsername();
                    RedisManager<Notifikacija>.Publish("PostavljenaObjava", new Notifikacija(ids, objavaID, Naziv, userId, userName));
                }
                finally { await session.CloseAsync(); }
            }
            finally
            {
                await session.CloseAsync();
            }

            return RedirectToAction("Index", "Home");
        }


     
        [HttpDelete]
        [Route("ObrisiNotifikaciju")]
        public IActionResult ObrisiNotifikaciju(string path, string item)
               => RedisManager<string>.DeleteItem(path, item) ? Ok() : BadRequest();

       
        [HttpGet]
        [Route("PromeniObjavu")]
        public async Task<IActionResult> PromeniObjavu(string id, string naziv, string sadrzaj, string tag)//radi ovo
        {
            if (!HttpContext.Session.IsLoggedIn())
            {
              
                return RedirectToAction("Login", "Home");
            }
            var objavaId = int.Parse(id);
            IAsyncSession session = _driver.AsyncSession();
            try
            {
                _ = await session.RunAsync($"MATCH (o:Objava) WHERE id(o)={objavaId} SET o = {{ naziv: '{naziv}', sadrzaj: '{sadrzaj}', tag: '{tag}' }} ");


            }
            finally
            {
                await session.CloseAsync();
            }
            
            return RedirectToAction("MojeObjave", "Home");
           
        }

       
        [HttpGet]
        [Route("ObrisiObjavu")]
        public async Task<IActionResult> ObrisiObjavu(int objavaID)
        {

            if (!HttpContext.Session.IsLoggedIn())
            {


                return RedirectToAction("Login", "Home");
            }
            IAsyncSession session = _driver.AsyncSession();
            try
            {
                _ = await session.RunAsync($"MATCH (n) WHERE id(n) = {objavaID} DETACH DELETE n");
            }
            finally
            {
                await session.CloseAsync();
            }
            return RedirectToAction("MojeObjave", "Home");
            
        }
        [HttpGet]
        [Route("Profil")]
        public async Task<IActionResult> Profil()
        {
            if (!HttpContext.Session.IsLoggedIn())
                return RedirectToAction("Login", "Home");
            

            var userId = HttpContext.Session.GetUserId();
            var session = _driver.AsyncSession();
            try
            {
                var result = await session.RunAsync($"MATCH (k:Korisnik) WHERE id(k) = {userId} RETURN k");
                var user = (await result.SingleAsync())["k"].As<INode>();
                string str_godinaStudija = user.Properties["godinaStudija"].ToString();

                return View(new Korisnik
                {
                    ID = userId,
                    KorisnickoIme = user.Properties["korisnickoIme"].ToString(),
                    Sifra = user.Properties["sifra"].ToString(),
                    Email = user.Properties["email"].ToString(),
                    Fakultet = user.Properties["fakultet"].ToString(),
                    Smer = user.Properties["smer"].ToString(),
                    GodinaStudije = Int32.Parse(str_godinaStudija)

                });
            }
            finally
            {
                await session.CloseAsync();
            }
           
        }
        
        }
}

NBP_I_PROJEKAT/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Http
@using NBP_I_PROJEKAT.Session
@using NBP_I_PROJEKAT.Models

@model Objave


@{ int userId = ViewContext.HttpContext.Session.GetInt32(SessionKeys.UserId) ?? -1;
    bool isLoged = userId >= 0; }


<div class="container-fluid">
    <div class="row">
        @*<div class="col-2  category-col">
            <div class="card card-shadow">
                <div class="card-body">
                    <h5 class="card-title">Tagovi:</h5><ul class="list-group">
                        @if (Model.TagList.Count > 0)
                        {
                            foreach (var item in Model.TagList)
                            {
            <li class="list-group-item d-flex justify-content-between align-items-center"><a asp-controller="Home" asp-action="Index" asp-route-category="@item.Naziv">@item.Naziv</a><span class="badge badge-primary badge-pill">@item.Objave.Count</span></li>}
                        }

                    </ul>
                </div>
            </div>
        </div>*@


        <div class="col-7">
            <div class="container">
                <div class="row main-row">
                    @if (Model.TagList.Count > 0)
                        foreach (var item in Model.TagList)
                        {
                            string tag = ViewContext.HttpContext.Request.Query.Count > 0 ? ViewContext.HttpContext.Request.Query["tag"].FirstOrDefault() : "";
                            var items = string.IsNullOrEmpty(tag) ? item.Objave : item.Objave.Where(x => x.Tag.Equals(tag));
        @foreach (var objava in items)
        {<div class="col-4 d-flex justify-content-center">
                <div class="card card-shadow" style="width: 18rem;">
                    <div class="card-body" style="display: inline-grid; background-color: wheat;">
                        <h4 class="card-title">Objava: @objava.Naziv</h4>
                        <h6 class="card-title" style="font-size:larger; ">Tag: #@objava.Tag</h6>
                        <h5 class="card-subtitle mb-2 text-muted">@*Cena: @ad.Price*@</h5>
                        <h6 class="card-title ">Kratak opis objave: </h6>
                        <h6 class="card-text">@objava.Sadrzaj</h6>
                        @if (isLoged)
                        {
                            <a asp-controller="Home" asp-action="PrikaziPojedinacneObjaveKorisnika" asp-route-objavaId="@objava.Id" class="btn btn-primary">Otvori</a>
                         

                                                        <a asp-controller="Home" asp-action="LajkujObjavuKorisnika" asp-route-objavaID="@objava.Id" class="btn btn-light">Oznaci svidjanje</a>

                                
                        }

                    </div>
                </div>
            </div>}}
                </div>
            </div>

        </div><div class="col-3 leaderboard-col">
            <div class="card card-shadow">
                <div class="card-body" style="background-color:wheat;">
                    <h5 class="card-title">Korisnici sa najvise lajkovanih objava</h5><table class="table">
                        <thead><tr><th scope="col">#</th><th scope="col">Ime</th><th scope="col">Ocene</th></tr></thead>
                        <tbody>
                            @{if (isLoged) {
                                    int i = 0;
                                    foreach (var item in Model.Leaderboard)
                                    {
                    <tr><th scope="row">@(++i)</th><td><a asp-controller="Home" asp-action="PrikaziSveObjaveKorisnika"  asp-route-userId="@item.userInfo.Id">@item.userInfo.Username</a></td><td class="text-success">@item.score</td></tr> } }
                                }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div> 
    @if (isLoged)
    {<div class="row m-2 pt-5">

            <div class="row m-2 pt-5">
                <div class="col-12 mb-3 text-light"><h3>Preporuke:</h3></div>
                @if (Model.ObjavaRecomendList != null)
                {
@foreach (var objava in Model.ObjavaRecomendList)
{<div class="col-4 d-flex justify-content-center">
        <div class="card card-shadow" style="width: 18rem;">
            <div class="card-body" style="background-color:wheat;">
                <h4 class="card-title">Objava: @objava.Naziv</h4>
                <h6 class="card-title" style="font-size:larger; ">Tag: #@objava.Tag</h6>
                <h6 class="card-title ">Kratak opis objave: </h6>
                <h6 class="card-text">@objava.Sadrzaj</h6>
                <a asp-controller="Home" asp-action="PrikaziPojedinacneObjaveKorisnika" asp-route-objavaId="@objava.Id" class="btn btn-primary">Otvori</a>
                
            </div>
        </div>
    </div>} }
else
{
<p>Nema dovoljno podataka! Niste jos nista lajkovali!</p>}
            </div>
        </div>}
</div>







<!-- Forma za prijavu -->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="loginModalLongTitle">Prijavi se</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post" asp-action="Prijava" asp-controller="Home">
                    <div class="form-group">
                        <label for="username">Korisničko ime</label>
                        <input type="text" name="username" class="form-control" id="username" placeholder="Korisničko ime">
                    </div>
                    <div class="form-group">
                        <label for="password">Lozinka</label>
                        <input type="password" name="password" class="form-control" id="password" placeholder="Lozinka">
                    </div>
                    <button type="submit" class="btn btn-primary">Prijavi se</button>
                </form>
            </div>
        </div>
    </div>
</div>




<!-- Forma za registraciju -->
<div class="modal fade" id="registerModal" tabindex="-1" role="dialog" aria-labelledby="registerModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="registerModalLongTitle">Registruj se</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form asp-action="Registracija" asp-controller="Home">
                    <div class="form-group">
                        <label for="username">Korisničko ime</label>
                        <input type="text" name="username" class="form-control" id="username" placeholder="Korisničko ime">
                    </div>
                    <div class="form-group">
                        <label for="email">Email adresa</label>
                        <input type="text" name="email" class="form-control" id="email" placeholder="Email adresa">
                    </div>
                    <div class="form-group">
                        <label for="fakultet">Fakultet</label>
                        <input type="text" name="fakultet" class="form-control" id="fakultet" placeholder="Fakultet">
                    </div>
                    <div class="form-group">
                        <label for="smer">Smer</label>
                        <input type="text" name="smer" class="form-control" id="smer" placeholder="Smer">
                    </div>
                    <div class="form-group">
                        <label for="godinaStudija">Godina Studija</label>
                        <input type="text" name="godinaStudija" class="form-control" id="godinaStudija" placeholder="Godina Studija">
                    </div>
                    <div class="form-group">
                        <label for="password">Lozinka</label>
                        <input type="password" name="password" class="form-control" id="password" placeholder="Šifra">
                    </div>
                    <div class="form-group">
                        <label for="register-password-confirm">Ponovite lozinku</label>
                        <input type="password" class="form-control" id="password-confirm" placeholder="Ponovite lozinku">
                    </div>
                    <button type="submit" class="btn btn-primary">Prijavi se</button>
                </form>
            </div>
        </div>
    </div>
</div>

NBP_I_PROJEKAT/Views/Home/KorisnikoveObjave.cshtml
@page
@using NBP_I_PROJEKAT.Models
@model List<Objava>

@{
   // ViewData["Title"] = "Objave";
}

<div class="container">
    <div class="row main-row d-flex justify-content-center">
        @if (Model.Count > 0)
            foreach (var o in Model)
            {
                <div class="col-3 mt-2 d-flex justify-content-center">
                    <div class="card card-shadow" style="width: 18rem;">
                        <div class="card-body">
                            <h5 class="card-title">@o.Naziv</h5>
                            <h6 class="card-subtitle mb-2 text-muted">Tag: @o.Tag</h6>
                            <p class="card-text">Sadrzaj: @o.Sadrzaj</p>
                            <a asp-controller="Objava" asp-action="PrikaziPojedinacneObjaveKorisnika" asp-route-objavaId="@o.Id" class="card-link">Otvori</a>
                        </div>
                    </div>
                </div>
            }
    </div>
</div>

NBP_I_PROJEKAT/Views/Home/MojeObjave.cshtml
@*@model NBP_I_PROJEKAT.Views.Home.MojeObjaveModel*@
@using NBP_I_PROJEKAT.Models
@using NBP_I_PROJEKAT.Controllers

@model List<Objava>





<div class="container">
    <div class="row main-row d-flex justify-content-center">
        @if (Model.Count > 0)
            foreach (var o in Model)
            {
                <div class="col-3 mt-2 d-flex justify-content-center">
                    <div class="card card-shadow" style="width: 18rem;">
                        <div class="card-body" style="background-color:wheat;">
                            <h4 class="card-title">Objava: @o.Naziv</h4>
                            <h6 class="card-title" style="font-size:larger; ">Tag: #@o.Tag</h6>
                            <h6 class="card-title ">Kratak opis objave: </h6>
                            <h6 class="card-text">@o.Sadrzaj</h6>
                            <button class="btn btn-primary" onclick="@($"OpenModalPopUp('{o.Id}', '{o.Naziv}', '{o.Tag}', '{o.Sadrzaj}')");">Izmeni</button>
                            <a asp-controller="Objava" asp-action="ObrisiObjavu" asp-route-objavaID="@o.Id" class="btn btn-danger">Obriši</a>
                        </div>
                    </div>
                </div>
            }
        else
        {
            <div>
                <label>Trenutno nemate ni jednu objavu!</label>
            </div>
        }
    </div>
</div>

<div class="modal fade" id="changeModal" tabindex="-1" role="dialog" aria-labelledby="changeModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="changeModalLongTitle">Izmeni objavu</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <input type="hidden" name="id" class="form-control" id="id">
                 
                    <div class="form-group">
                        <label for="Tag">Tag objave</label>
                        <input type="text" name="Tag" class="form-control" id="Tag">
                    </div>
                    <div class="form-group">
                        <label for="Naziv">Naziv objave</label>
                        <input type="text" name="Naziv" class="form-control" id="Naziv">
                    </div>
                   
                    <div class="form-group">
                        <label for="Sadrzaj">Sadrzaj objave</label>
                        <input type="text" name="Sadrzaj" class="form-control" id="Sadrzaj">
                    </div>
                    <button type="submit" class="btn btn-danger" asp-action="PromeniObjavu" asp-controller="Objava">Izmeni</button>
                    <button type="submit" class="btn btn-primary" asp-action="MojeObjave" asp-controller="Home">Odustani</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    function OpenModalPopUp(id, naziv, tag, sadrzaj) {
        let strId = id.toString();
        $('#id').val(strId);
        $('#tag').val(tag);
        $('#naziv').val(naziv);
        $('#sadrzaj').val(sadrzaj);
        $("#changeModal").modal();
    }
</script>